name: Test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Initializate
        uses: actions/checkout@v3

      - name: Mount Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name:  env file
        run: |
          echo "DATABASE_URL=postgresql://test:test@localhost:5432/test" > .env
          echo "NODE_ENV=local" > .env
          
      - name: Wait for DB
        run: |
          for i in {1..30}; do
            nc -z localhost 5432 && echo "Postgres is ready" && exit 0
            echo "Waiting for DB..."
            sleep 2
          done
          echo "Postgres failed to start" && exit 1

      - name: Unit Tests
        run: npm test
